# Generated by Django 3.1.2 on 2021-01-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='shipping_address',
            new_name='address',
        ),
    ]
